# Generated by Django 5.2.8 on 2025-11-15 06:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=100)),
                ('meta_description', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('page_title', models.CharField(max_length=30)),
                ('hero_background', models.ImageField(blank=True, null=True, upload_to='core/hero/')),
                ('hero_description', models.TextField(blank=True)),
                ('main_content', ckeditor.fields.RichTextField(blank=True, help_text='WYSIWYG content for the main section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='core/featured/')),
            ],
            options={
                'verbose_name': 'Core Page',
                'verbose_name_plural': 'Core Pages',
            },
        ),
    ]
