# Generated by Django 5.2.8 on 2025-11-15 06:51

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_corepage_main_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corepage',
            name='main_content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='WYSIWYG content for the main section', verbose_name='Main content'),
        ),
    ]
