# Generated by Django 5.2.8 on 2025-11-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_corepage_main_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='corepage',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
